FROM public.ecr.aws/bitnami/node:18.20.2-debian-12-r6

# Define ARGs
ARG NEXT_PUBLIC_AUTH_API_URL
ARG NEXT_PUBLIC_MATCHMAKING_API_URL
ARG NEXT_PUBLIC_GAME_STATE_API_URL
ARG NEXT_PUBLIC_BETTING_WAGER_API_URL
ARG NEXT_PUBLIC_MESSAGING_API_URL
ARG NEXT_PUBLIC_PAYMENTS_API_URL
ARG NEXT_PUBLIC_LEADERBOARD_RANKING_API_URL
ARG NEXT_PUBLIC_CHEAT_DETECTION_API_URL
ARG NEXT_PUBLIC_DISPUTE_RESOLUTION_API_URL

# Set ENV vars (used by Next.js build/runtime)
ENV NEXT_PUBLIC_AUTH_API_URL=$NEXT_PUBLIC_AUTH_API_URL
ENV NEXT_PUBLIC_MATCHMAKING_API_URL=$NEXT_PUBLIC_MATCHMAKING_API_URL
ENV NEXT_PUBLIC_GAME_STATE_API_URL=$NEXT_PUBLIC_GAME_STATE_API_URL
ENV NEXT_PUBLIC_BETTING_WAGER_API_URL=$NEXT_PUBLIC_BETTING_WAGER_API_URL
ENV NEXT_PUBLIC_MESSAGING_API_URL=$NEXT_PUBLIC_MESSAGING_API_URL
ENV NEXT_PUBLIC_PAYMENTS_API_URL=$NEXT_PUBLIC_PAYMENTS_API_URL
ENV NEXT_PUBLIC_LEADERBOARD_RANKING_API_URL=$NEXT_PUBLIC_LEADERBOARD_RANKING_API_URL
ENV NEXT_PUBLIC_CHEAT_DETECTION_API_URL=$NEXT_PUBLIC_CHEAT_DETECTION_API_URL
ENV NEXT_PUBLIC_DISPUTE_RESOLUTION_API_URL=$NEXT_PUBLIC_DISPUTE_RESOLUTION_API_URL

RUN apt-get update

# Create app directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy source code
COPY . .

# Add this line before the build command
#RUN npx prisma generate

# Build Next.js application
ENV NEXT_PUBLIC_APP_ENV=production
RUN npm run build

# Expose port 80
EXPOSE 80

# Start Next.js
ENV PORT=80
CMD ["node", "node_modules/.bin/next", "start", "-p", "80"]
